### PR TITLE
improved humanize ordinal

### PR DESCRIPTION
**Pull request by Sreyas-Sreelal**

### CODE REVIEW

**Comment by thecodeah** [comment]
This would concatenate the ordinal to dest[]. Was this done on purpose?
I'm just wondering whether it's a better idea to concatenate or to move the null terminator to the beginning of the string first.

**Comment by Sreyas-Sreelal** [comment]
i was confused whether you wanted a void function.I think returning some information about can be useful.It's up to you.

**Comment by thecodeah** [comment]
Yeah I think the best option is to first just append the number to dest[] so that when it is used, it won't be completely empty as well as returning 0.

**Comment by Sreyas-Sreelal** [comment]
yes you are right i didn't thought about the situation of passing an used array

**Pull request merged**
